export const SPLITWISE_THEME = "SPLITWISE_THEME";
export const SPLITWISE_USER = "SPLITWISE_USER";
export const SPLITWISE_FRIENDS = "SPLITWISE_FRIENDS";
export const SPLITWISE_EXPENSES = "SPLITWISE_EXPENSES";
export const SPLITWISE_EXPENSE_DATA = "SPLITWISE_EXPENSE_DATA";
export const SPLITWISE_TRACK_USERS = "SPLITWISE_TRACK_USERS";

export const ADD_FRIEND_REQUEST = "ADD_FRIEND_REQUEST";
export const ADD_FRIEND_FAILED = "ADD_FRIEND_FAILED";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";

export const GET_FRIENDS_REQUEST = "GET_FRIENDS_REQUEST";
export const GET_FRIENDS_FAILED = "GET_FRIENDS_FAILED";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_FAILED = "GET_USER_FAILED";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const ADD_EXPENSES_REQUEST = "ADD_EXPENSES_REQUEST";
export const ADD_EXPENSES_SUCCESS = "ADD_EXPENSES_SUCCESS";
export const ADD_EXPENSES_FAILED = "ADD_EXPENSES_FAILED";

export const GET_EXPENSES_REQUEST = "GET_EXPENSES_REQUEST";
export const GET_EXPENSES_SUCCESS = "GET_EXPENSES_SUCCESS";
export const GET_EXPENSES_FAILED = "GET_EXPENSES_FAILED";

export const SET_THEME_REQUEST = "SET_THEME_REQUEST";
export const SET_THEME_SUCCESS = "SET_THEME_SUCCESS";
export const SET_THEME_FAILED = "SET_THEME_FAILED";

export const GET_THEME_REQUEST = "GET_THEME_REQUEST";
export const GET_THEME_SUCCESS = "GET_THEME_SUCCESS";
export const GET_THEME_FAILED = "GET_THEME_FAILED";
